### PR TITLE
fixes the GetFinalType for Nested Enumerable

### PR DESCRIPTION
**Pull request by pksorensen**
Fixes 

https://github.com/unitycontainer/container/issues/72
https://github.com/unitycontainer/microsoft-dependency-injection/issues/15

### CODE REVIEW

**Comment by ENikS** [comment]
@pksorensen  Your PR breaks a lot of tests.
Get the Unity repo and try to build it with your change, you will see tests from Unity.Specification failing right and left :)

**Comment by pksorensen** [comment]
hmm, i must have overlooked those tests. sorry. 

I dont know what the proper fix is then.

**Comment by ENikS** [comment]
I am working on Wiki article and example about it. 
It two words you need to implement factory to make your generics look like built in type so IsRegistered would not see it.

**Comment by pksorensen** [comment]
But dont that mean we cant use it with aspnet core as theres no way I can enforce aspnet core team and people doing things for aspnet core to set their stuff up correct for unity.

**Comment by pksorensen** [comment]
also took a look at the specification tests but they only depend on the abstraction library so I dont understand why i can break tests there when I only did change the implementation :)

**Comment by ENikS** [comment]
Did you try to build and run them?

**Comment by pksorensen** [comment]
I think I am missing something. I am cloning everything and then creating a solution where i add all projects to get the nuget/dotnet restore to work. (so i did test the tests of Unity.Container. 

Did not know about the specification tests. I then cloned those and added it (and saw the reference to Unity.Abstraction but not Unity.Container) so no I have not run the specification tests.

This is what you get in Visual studio if you clone and try to build without manually starting to fix references.

image


I am trying to figure this out. 

Whats your comment on

> But dont that mean we cant use it with aspnet core as theres no way I can enforce aspnet core team and people doing things for aspnet core to set their stuff up correct for unity.

**Comment by ENikS** [comment]
Ok, step by step:
- clone [Unity](https://github.com/unitycontainer/unity.git) https://github.com/unitycontainer/unity.git
- checkout v5.x
- update submodules
- open package.sln from root in Visual Studio
- build
- It shoud discover 1306 tests
- run these tests

**Comment by pksorensen** [comment]
thanks. I will give it a go and try. Maybe (if its not already there) this would be nice to have in the readme as i just click clone in visualstudio button on github - and it dont clone submodules which is what I assume to be missing for me. 

Will try to create a fix that dont break stuff then. if its possible, as i am not sure if if 

> The container should be able to resolve chain of generics like this: IEnumerable<Lazy<IList>> if T is registered.

is complient with aspnet core dependency injection

**Comment by pksorensen** [comment]
Command was 
```
git clone --recurse-submodules -b v5.x https://github.com/unitycontainer/unity.git
```
and build + test and all 1306 test succeded.  

Would have saved me some time knowing this some weeks ago :) Thanks.  I will try continue. We can close this for now.

**Comment by ENikS** [comment]
Could you add it to README.md? I am trying to finish examples before Monday...

**Comment by pksorensen** [comment]
Yes, i will add a PR for readme within the next few days when i played abit more with it.

Btw, i have moved back to my own enumerable extension until I figure out if this will become compatible with aspnet core.

```
    public class EnumerableExtension : UnityContainerExtension
    {
        protected override void Initialize()
        {
            // Enumerable strategy
            Context.Strategies.Add(new EnumerableResolutionStrategy(),
                UnityBuildStage.Setup);

        }
    }
```
which inject my own implementation before the one default in unity right now. 

I will try see if I can figure out a better fix

**Comment by ENikS** [comment]
I think the way to go is to fix the Unity...web package.

**Comment by pksorensen** [comment]
@ENikS I just added another commit, do you have some feedback? 

I simply forgot that Func<> also should be checked.

**Comment by ENikS** [comment]
It breaks all of [these](https://github.com/unitycontainer/specification-tests/blob/master/src/Resolution/Array.cs)

**Comment by pksorensen** [comment]
hmm its all green here.

**Comment by pksorensen** [comment]
hmm, there is also still only one commit here. Need to figure out why it was not pushed the extra commit. 2sec

**Comment by pksorensen** [comment]
Ahh, now its there. Its all green here now.

**Comment by ENikS** [comment]
You are killing performance with your approach. It needs to be fast. Hashset is not. How about we try to address it in Web solution?
Do you have a test project I could look at?

**Comment by pksorensen** [comment]
Okay. Fair point.

Would it be fine if I create a reproduction of the issue in Microsoft.DependencyInjection.Tests unit tests and we can solve it there as an example?

I can also create a small website to repro the issue. 

What do you prefer?

**Comment by pksorensen** [comment]
You can also easily test it locally by the following test:

```
using System;
using IdentityServer4.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Specification;
using Xunit;

namespace Unity.Microsoft.DependencyInjection.Tests
{

   
    public class Tests : DependencyInjectionSpecificationTests
    {
        protected override IServiceProvider CreateServiceProvider(IServiceCollection serviceCollection)
        {
            return serviceCollection.BuildServiceProvider();
        }


      
        [Fact]
        public void Test13()
        {
            var c = new UnityContainer();

            var sc = new ServiceCollection();



            sc.AddIdentityServer(o =>
            {
                o.Events.RaiseErrorEvents = true;
            });

            var sp = ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(sc);

            var test = sp.GetService<IdentityServerOptions>();

            Assert.NotNull(test); //Passes


            var sp1 = sc.BuildServiceProvider(c);


            var test1 = sp1.GetService<IdentityServerOptions>();

            Assert.NotNull(test1);

        }
    }
}
```

and adding 

```
    <PackageReference Include="IdentityServer4" Version="2.1.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
```

to Microsoft.DependencyInjection.Tests.csproj

**Comment by ENikS** [comment]
Did you see [this wiki](https://github.com/unitycontainer/unity/wiki/Upgrading-to-Release-5.8.x)?

**Comment by pksorensen** [comment]
Nope, i am taking a look

**Comment by pksorensen** [comment]
I think I understand it and will take some time to get familiar with the buildplan factories examlpes. 

I understand it as I could create a buildplan factory that makes all the aspnet core generics build in types which should resolve the problem.

Let me try it out and get back with feedback

**Comment by ENikS** [comment]
I would prefer if you add small test project to [this](https://github.com/unitycontainer/examples/tree/master/src/web) directory

**Comment by ENikS** [comment]
What are these types you talking about? Do you have a list?

**Comment by ENikS** [comment]
Lets open an issue in DependencyInjection repo.

**Comment by pksorensen** [comment]
Add this time I only have the one from aspnet core Options.

From this exception stack.
```
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving Microsoft.Extensions.Options.OptionsManager`1[IdentityServer4.Configuration.IdentityServerOptions],(none) (mapped from Microsoft.Extensions.Options.IOptions`1[IdentityServer4.Configuration.IdentityServerOptions], (none))
  Resolving parameter 'factory' of constructor Microsoft.Extensions.Options.OptionsManager`1[[IdentityServer4.Configuration.IdentityServerOptions, IdentityServer4, Version=2.1.3.0, Culture=neutral, PublicKeyToken=null]](Microsoft.Extensions.Options.IOptionsFactory`1[[IdentityServer4.Configuration.IdentityServerOptions, IdentityServer4, Version=2.1.3.0, Culture=neutral, PublicKeyToken=null]] factory)
    Resolving Microsoft.Extensions.Options.OptionsFactory`1[IdentityServer4.Configuration.IdentityServerOptions],(none) (mapped from Microsoft.Extensions.Options.IOptionsFactory`1[IdentityServer4.Configuration.IdentityServerOptions], (none))
    Resolving parameter 'postConfigures' of constructor Microsoft.Extensions.Options.OptionsFactory`1[[IdentityServer4.Configuration.IdentityServerOptions, IdentityServer4, Version=2.1.3.0, Culture=neutral, PublicKeyToken=null]](System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Options.IConfigureOptions`1[[IdentityServer4.Configuration.IdentityServerOptions, IdentityServer4, Version=2.1.3.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Extensions.Options, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] setups, System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Options.IPostConfigureOptions`1[[IdentityServer4.Configuration.IdentityServerOptions, IdentityServer4, Version=2.1.3.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Extensions.Options, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] postConfigures)
      Resolving System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IPostConfigureOptions`1[IdentityServer4.Configuration.IdentityServerOptions]],(none)
        Resolving Microsoft.Extensions.Options.IPostConfigureOptions`1[IdentityServer4.Configuration.IdentityServerOptions],(none)
```

So one would be: Microsoft.Extensions.Options.IPostConfigureOptions 


I guess you did not see my issue there already: https://github.com/unitycontainer/microsoft-dependency-injection/issues/15

**Pull request closed without merging**
