### PR TITLE
issue 231 repo

### PR DESCRIPTION
**Pull request by hanabi1224**

### CODE REVIEW

**Comment by hanabi1224** [comment]
Wow, looks like CI does not run tests

**Comment by ENikS** [comment]
What are we testing here? 
There are tests for the factory already in the project.

**Comment by ENikS** [comment]
Could you please limit your PR to just the [test](https://github.com/hanabi1224/container/blob/7bbdbe6c22f0bc0b41fd13b13eb259bc2b5ec878/tests/Unity.Tests/Issues/FactoryResolve.cs) and squash your commits? 

I'd rather not update project and config files at the moment.

**Comment by ENikS** [comment]
This is not necessary. See [the issue](https://github.com/unitycontainer/unity/issues/231)

**Pull request closed without merging**
