### PR TITLE
#108: Added parametrized version of GetOrAdd, so child containers can…

### PR DESCRIPTION
**Pull request by bartoszkp**
… pass up their own way of creating a new registration. This way child container strategies will be used when creating a build child for a new registration.

### CODE REVIEW

**Comment by ENikS** [comment]
Unfortunately this is not going to work.

The proper way of doing it is by [creating new instance](https://github.com/unitycontainer/container/blob/4c5672d0e2ca38edef1d627a6395b536c4d27c52/src/UnityContainer.Implementation.cs#L66) of ``StagedStrategyChain`` for the child container instead of just [getting reference from parent](https://github.com/unitycontainer/container/blob/9b5f526fc44f77c841af893fdd9ff3e6a3de6849/src/UnityContainer.Implementation.cs#L186).

This is one of these things that been optimized out of original version. If you look at original implementation it was done properly but later has been simplified. I was going to add it back later but never had time.

The idea is to create new instance only if collection of strategies has been modified. Once created it should monitor changes made in parent lists down the parent chain.

If you want to try implementing this logic properly I would help with advise and any info...

**Comment by bartoszkp** [comment]
Yes, I can give it another try. Any hints would be welcome! :)

**Comment by ENikS** [comment]
``GetOrAdd`` should be replaced with proper implementation based on strategies override. Look how [these methods](https://github.com/unitycontainer/container/blob/9b5f526fc44f77c841af893fdd9ff3e6a3de6849/src/UnityContainer.Implementation.cs#L109-L112) are implemented. They are initialized with different implementation depending on container having its own registrations. Same should be done for the strategies.

**Comment by ENikS** [comment]
The registration should be constructed where it is registered. Consider a child container's registration an override. Same should apply to strategies. if you have a child with custom build chain it should serve as a root for all children using that build chain.

If you think about it, it is not that simple. This is why I was putting it off for so long

**Comment by bartoszkp** [comment]
OK, sorry but probably I'm still missing a lot of things. The following makes all the tests pass: https://gist.github.com/bartoszkp/414b8dd7eb3915dc94e1010ecf4bba51 but looks suspiciously simple, wrt your explanations. If it's still wrong, I think I understand too little to deal with this task... :)

**Comment by ENikS** [comment]
I would start with creating a new set of tests for the behavior you are trying to implement. 
- Adding new build strategy, how it affect creation of new types on this, parent, and child containers
- Registering new types on this/parent/child container, how it interact with new strategy
- etc.

Existing tests will not cover the behavior you are trying to test.

**Comment by bartoszkp** [comment]
I'm not sure I know what are the requirements. For example, should the container be stateless from the client's perspective? Could you provide a little more details on particular scenarios and their invariants I need to test? For example, I've created the following two tests - indeed, after my fix the first one fails (the failure is indicated by the comment): https://gist.github.com/bartoszkp/84f0661ebea9c445923861353656fc54

**Comment by ENikS** [comment]
Why are you trying to implement it? Could you solve your issue without adding this change?
I am working on v5.9.0 and perhaps this could wait until it is out? A lot of internals will change in this version.

**Comment by bartoszkp** [comment]
We have a very complicated and large hierarchy of containers, with a lot of custom strategies. We've recently upgraded from Unity 2 and this is one of the things that stopped working for us. Could you estimate when v5.9 might be out?

**Comment by ENikS** [comment]
I would say a month or two. But if you say you are working on upgrade from v2.1, why don't you copy the implementation and tests from [here](https://github.com/unitycontainer/unity/blob/816421af46b099232750b512e323fed1f34ee6a0/Unity/Unity/Src/UnityContainer.cs#L550)? This is how it used to be implemented, you just need to replicate the behavior.

**Comment by bartoszkp** [comment]
I will give it a try tomorrow. Month is quite long so it would be great if it would be possible to fix this earlier. Thanks!

**Pull request closed without merging**
