### PR TITLE
If container is null, a NullReferenceException  is thrown

### PR DESCRIPTION
**Pull request by pksorensen**

### CODE REVIEW

**Comment by pksorensen** [comment]
Dont know if its needed.

Could be that some refactoring did so my own aspnet core dependency injection implementation broke.


In my builder strategy i had this code
```
 private IUnityContainer GetUnityFromBuildContext(IBuilderContext context)
        {
            return context.Container;
            //var lifetime = context.Policies.Get<ILifetimePolicy>(NamedTypeBuildKey.Make<IUnityContainer>());
            //try
            //{
            //    return lifetime.GetValue() as IUnityContainer;
            //}catch(Exception ex)
            //{
            //    return null;
            //}
        }
```
where the commented out code was what caused my problem. Fixed it by returning context.Container and the PR is not needed.

In my own implementation, this test succeds,

```
    public interface MyTest
    {

    }
    public class MyTestClass
    {
        public MyTestClass(MyTest dependency = null)
        {
            Assert.IsNull(dependency);
        }
    }

 
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void ShouldUseDefaultValue()
        {
            //My own implementation, works
            //var container = new UnityContainer().WithAspNetCoreServiceProvider();
            //container.Resolve<MyTestClass>();


            var c = new UnityContainer();
            var spf = new ServiceProviderFactory(c);

            var cc = spf.CreateBuilder(new ServiceCollection());
            cc.Resolve<MyTestClass>();
        }
    }
```

but it fails with the ServiceProviderFactory implementation here, as it do not allow default values when. 
I wonder why this was not tested in the aspnet core DI tests, as i am pretty sure i had some resolution fails wiht MVC when i first implemented my own builder strategy (but this was back at 1.1) so maybe its not needed any more.

**Comment by pksorensen** [comment]
@ENikS should i add my test and question to the other repository for aspnet core or can we continue the discussion here?

**Comment by ENikS** [comment]
Here is fine

**Comment by pksorensen** [comment]
What do you think, should the test i posted fail or succed?

I argue that it should be able to resolve MyTestClass as its constructor parameters are resolvable by default values. interface MyTest should not be registered.

**Comment by ENikS** [comment]
Unity does not understand default values. It will fail to resolve public 
```
MyTestClass(MyTest dependency = null)
```

**Comment by pksorensen** [comment]
okay. If its not an issue anymore with aspent core MVC, then i am fine with it.

In 1.1 there was some services that depended on IHttpContextFactory factory = null and unity failed if it was not registered.

I will try test it next time and come back with the result

**Comment by pksorensen** [comment]
hi again @ENikS 

I have done some tests, and I cant swap to your implementation just yet of aspnet core dependency injection.

There are examples around aspnet core where they make use of default values = null.

First example that i found that blocked me:
https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/9e9e5be11bc19fdcf9cadf4b6752de0abf80512f/src/IdentityModel.AspNetCore.OAuth2Introspection/OAuth2IntrospectionHandler.cs#L40

This means that dependencies will return null where not expected here:

```
        public object GetService(Type serviceType)
        {
            try
            {
                return _container.Resolve(serviceType);
            }
            catch  { /* Ignore */}

            return null;
        }
```
heres the exception that is swallowed up:
```
Unity.Exceptions.ResolutionFailedException: 'Resolution of the dependency failed, type = 'Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions]', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, Microsoft.Extensions.Caching.Distributed.IDistributedCache, is an interface and cannot be constructed. Are you missing a type mapping?
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving Microsoft.Extensions.Options.OptionsMonitor`1[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions],(none) (mapped from Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions], (none))
  Resolving parameter 'factory' of constructor Microsoft.Extensions.Options.OptionsMonitor`1[[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions, IdentityModel.AspNetCore.OAuth2Introspection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null]](Microsoft.Extensions.Options.IOptionsFactory`1[[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions, IdentityModel.AspNetCore.OAuth2Introspection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null]] factory, System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Options.IOptionsChangeTokenSource`1[[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions, IdentityModel.AspNetCore.OAuth2Introspection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Extensions.Options, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] sources, Microsoft.Extensions.Options.IOptionsMonitorCache`1[[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions, IdentityModel.AspNetCore.OAuth2Introspection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null]] cache)
    Resolving Microsoft.Extensions.Options.OptionsFactory`1[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions],(none) (mapped from Microsoft.Extensions.Options.IOptionsFactory`1[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions], (none))
    Resolving parameter 'postConfigures' of constructor Microsoft.Extensions.Options.OptionsFactory`1[[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions, IdentityModel.AspNetCore.OAuth2Introspection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null]](System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Options.IConfigureOptions`1[[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions, IdentityModel.AspNetCore.OAuth2Introspection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Extensions.Options, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] setups, System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Options.IPostConfigureOptions`1[[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions, IdentityModel.AspNetCore.OAuth2Introspection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Extensions.Options, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] postConfigures)
      Resolving System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions]],(none)
        Resolving IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions,(none) (mapped from Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions], (none))
        Resolving parameter 'cache' of constructor IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions(Microsoft.Extensions.Caching.Distributed.IDistributedCache cache)
          Resolving Microsoft.Extensions.Caching.Distributed.IDistributedCache,(none)
```

and there are also examples in the aspnet core libs from microsoft. (will have to find them also, now this was just the first one that i ran into).

The solution is that the ConstructorSelectorPolicy needs to allow returning null when the argument has default values. I did this in my own implementation and will try to come up with a pull request for it.

**Pull request merged**
